### ISSUE TITLE
Things Todo

### ISSUE THREAD

**Issue by kylegalloway** [kylegalloway/kylegalloway.github.io#2]
- [x] Fix the about page.
- [x] Add links to github, twitter on layouts
- [x] Merge with master
- [x] Be sure all links on page are working

Based on http://joshualande.com/jekyll-github-pages-poole/
